image: ripsawridge/ruby-rsync:latest

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec rails s --daemon
  - bundle exec rake static:generate
  artifacts:
    paths:
    - public
  only:
  - master
