image: ripsawridge/ruby-rsync:latest

stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
   - vendor/bundler
   - public

rspec:
  stage: test
  environment:
    name: test
  services:
    - postgres:latest
  script:
    # use postgres service db config for ci testing
    - cp config/database.gitlab.yml config/database.yml
    - bundle install --path=vendor/bundler --without development
    - RAILS_ENV=test bundle exec rake db:migrate
    - RAILS_ENV=test bundle exec rspec

build:
  stage: build
  services:
    - postgres:latest
  script:
  - bundle install --path=vendor/bundler --without development test
  - bundle exec rails server -e static --daemon
  - bundle exec rake static:generate

pages:
  stage: deploy
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    policy: pull
  environment:
    name: static
    url: https://www.jpalmieri.com
  script: echo "deploying site to pages..."
  artifacts:
    paths:
    - public
  only:
  - master
